//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_PRACTICAS_DEFINITIVO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada_Persona
    {
        public int Id { get; set; }
        public int Id_Persona { get; set; }
        public int Id_Experiencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Dni { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Experiencia Experiencia { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
