//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_PRACTICAS_DEFINITIVO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeGusta
    {
        public int Id { get; set; }
        public Nullable<int> Id_Opinion { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Opinion Opinion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
