//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_PRACTICAS_DEFINITIVO.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MeetFeverDatos : DbContext
    {
        public MeetFeverDatos()
            : base("name=MeetFeverDatos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emoticono> Emoticonoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Entrada_Persona> Entrada_Persona { get; set; }
        public virtual DbSet<Experiencia> Experiencias { get; set; }
        public virtual DbSet<MeGusta> MeGustas { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Seguidor_Seguido> Seguidor_Seguido { get; set; }
        public virtual DbSet<Sexo> Sexoes { get; set; }
        public virtual DbSet<SIDA_EMPRESA_PRUEBA_GONZALO> SIDA_EMPRESA_PRUEBA_GONZALO { get; set; }
        public virtual DbSet<SIDA_PERSONA_PRUEBA_GONZALO> SIDA_PERSONA_PRUEBA_GONZALO { get; set; }
        public virtual DbSet<SIDA_USUARIO_PRUEBA_GONZALO> SIDA_USUARIO_PRUEBA_GONZALO { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Registro> Registroes { get; set; }
    
        public virtual int PA_Actualizar_Emoticono(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Emoticono", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Empleado(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Empleado", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Empresa(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Empresa", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Experiencia(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Experiencia", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Opinion(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Opinion", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Perfil(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Perfil", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Persona(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Persona", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Actualizar_Sexo(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualizar_Sexo", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Emoticono_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Emoticono_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Empleado_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Empleado_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Empresa_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Empresa_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Experiencia_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Experiencia_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_MeGusta_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_MeGusta_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Opinion_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Opinion_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Perfil_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Perfil_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Persona_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Persona_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_seguidor_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_seguidor_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Logico_Sexo_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Logico_Sexo_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Emoticono_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Emoticono_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Empleado_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Empleado_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Empresa_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Empresa_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Experiencia_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Experiencia_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_MeGusta_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_MeGusta_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Opinion_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Opinion_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Perfil_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Perfil_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Persona_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Persona_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_seguidor_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_seguidor_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Borrado_Real_Sexo_Por_ID(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Borrado_Real_Sexo_Por_ID", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Emoticono(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Emoticono", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Empleado(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Empleado", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Empresa(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Empresa", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Entrada_Persona(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Entrada_Persona", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Experiencia(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Experiencia", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Opinion(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Opinion", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Perfil(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Perfil", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Persona(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Persona", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Registro_De_Error(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Registro_De_Error", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Insertar_Sexo(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Insertar_Sexo", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_MeGusta(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MeGusta", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Empelados_Por_Empresa(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Empelados_Por_Empresa", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Empresa_Por_Cif(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Empresa_Por_Cif", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Empresa_Por_Correo(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Empresa_Por_Correo", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Empresa_Por_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Empresa_Por_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Empresa_Por_Nick(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Empresa_Por_Nick", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Experiencias_Por_Empresa(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Experiencias_Por_Empresa", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Experiencias_Por_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Experiencias_Por_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_MeGustas_Por_ID_Opinion(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_MeGustas_Por_ID_Opinion", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Opinion_Por_Autor(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Opinion_Por_Autor", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Opinion_Por_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Opinion_Por_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Opinion_Por_Id_Empresa(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Opinion_Por_Id_Empresa", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Opinion_Por_Id_Experiencia(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Opinion_Por_Id_Experiencia", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Persona_Por_Correo(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Persona_Por_Correo", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Persona_Por_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Persona_Por_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Persona_Por_Nick(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Persona_Por_Nick", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Persona_Por_Nombre(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Persona_Por_Nombre", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Seguidores_Usuario_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Seguidores_Usuario_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Seguidos_Usuario_ID(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Seguidos_Usuario_ID", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todas_Empresas(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todas_Empresas", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todas_Experiencias(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todas_Experiencias", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todas_Opiniones(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todas_Opiniones", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todas_Personas(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todas_Personas", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Seguir(string jSON_IN, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Seguir", jSON_INParameter, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAG_Iniciar_Sesion(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAG_Iniciar_Sesion", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAG_Top_10_Empresas(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAG_Top_10_Empresas", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAG_Top_10_Personas(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAG_Top_10_Personas", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAGA_Obtener_100_Opiniones_Mas_MG_Ultimas_24h(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGA_Obtener_100_Opiniones_Mas_MG_Ultimas_24h", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAGA_Obtener_4_Experiencias_Mas_Mencionadas_En_Opiniones(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGA_Obtener_4_Experiencias_Mas_Mencionadas_En_Opiniones", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAGA_Personas_Que_Quizas_Conozca(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGA_Personas_Que_Quizas_Conozca", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PAGA_Todas_Personas_Que_Quizas_Conozca(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGA_Todas_Personas_Que_Quizas_Conozca", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int PA_Obtener_Entradas_Por_Experiencia(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Entradas_Por_Experiencia", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todos_Emoticonos(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todos_Emoticonos", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todos_Perfiles(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todos_Perfiles", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Obtener_Todos_Sexos(ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Obtener_Todos_Sexos", jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    
        public virtual int PA_Is_MeGusta(string jSON_IN, ObjectParameter jSON_OUT, Nullable<int> iNVOKER, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var jSON_INParameter = jSON_IN != null ?
                new ObjectParameter("JSON_IN", jSON_IN) :
                new ObjectParameter("JSON_IN", typeof(string));
    
            var iNVOKERParameter = iNVOKER.HasValue ?
                new ObjectParameter("INVOKER", iNVOKER) :
                new ObjectParameter("INVOKER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Is_MeGusta", jSON_INParameter, jSON_OUT, iNVOKERParameter, rETCODE, mENSAJE);
        }
    }
}
