//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_PRACTICAS_DEFINITIVO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.MeGustas = new HashSet<MeGusta>();
            this.Opinions = new HashSet<Opinion>();
            this.Seguidor_Seguido = new HashSet<Seguidor_Seguido>();
            this.Seguidor_Seguido1 = new HashSet<Seguidor_Seguido>();
        }
    
        public int Id { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Nick { get; set; }
        public string Foto_Perfil { get; set; }
        public string Foto_Fondo { get; set; }
        public string Telefono { get; set; }
        public string Frase { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeGusta> MeGustas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguidor_Seguido> Seguidor_Seguido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguidor_Seguido> Seguidor_Seguido1 { get; set; }
    }
}
